#!/bin/bash

# orgserver
#
#     Start the org-mode data server, on the specified org data Git
# repository $ORG, with the specified projects $PRO.  Attempts to
# refresh the org data and project with "git pull origin master".  If
# changes are detected in the source, attempts to restart the server.
#
#     Can be run with a cron job to regularly refresh the org data,
# and attempt to restart the server.
#

export PYTHONPATH=/usr/local/lib/python2.7/site-packages:${PYTHONPATH}

RUN="${0##*/}-$( printf "%05d" $$ ):"
DIR=${0%/*}
ORG=${ORG_DIRECTORY:-~/org}
PRO=${ORG_PROJECTS:-}
RES=0 # restart any running server
REF=0 # refresh git repos
PID=${ORG}/orgserver.pid # +.##### contains PID of this orgserver's orgserver.py
OPT="--server=web.py --address 0.0.0.0:8080 --redundant"

while (( $# > 0 )); do
    if [[ "$1" == "--restart" ]]; then
        RES=1
    elif [[ "$1" == "--refresh" ]]; then
        REF=1
    elif [[ "$1" == "--org" ]]; then
        shift
        ORG=${1}
    elif [[ "$1" == "--help" ]]; then
        echo "${RUN} [--help] [--refresh] [--restart] [--org <dir>] [<project> ...]"
        echo "    --help      This help"
        echo "    --restart   Restart any running server"
        echo "    --refresh   Refresh Git repositories"
        echo "    --org <dir> org-mode data Git repository (default: ~/org)"
        echo "    <project>   <project>.org files to parse (default: project.org)"
    else
        # All remaining options are projects
        PRO="${PRO}${PRO:+ }${1}"
    fi
    shift
done

echo "${RUN} Directory: ${ORG}"
echo "${RUN} Projects:  ${PRO}"

# Kill our orgserver.py and clean up our PID file on exit
trap cleanup EXIT
cleanup () {
    kill $( cat $PID.$$ )
    rm -f $PID.$$
}

if (( REF )); then
    echo "${RUN} Refreshing $ORG..."
    ( cd $ORG && git pull origin master )
fi

(
    cd $DIR
    master=$( git show --oneline )
    if (( REF )); then
        echo "${RUN} Refreshing $DIR..."
        git pull origin master
        if [[ "$( git show --oneline )" != "$master" ]]; then
            echo "Detected $DIR update"
            RES=1
        fi
    fi
    if (( RES )); then
        echo "${RUN} Restarting orgserver.py"
        for pid in $PID.*; do
            if [ -f $pid ]; then
                kill $( cat $pid )
                rm $pid
            fi
            sleep 1
        done
    fi
)

# Run the python orgserver.py, savings its PID, and waiting 'til it exits.
# Since web.py access all /static content relative to its CWD, ensure that we
# change directory to the proper target before executing.
CMD="./orgserver.py ${OPT} ${ORG} ${PRO}"
echo "${RUN} In $DIR, starting: $CMD"
cd $DIR && $CMD &
echo $! >> $PID.$$
wait $!
if (( $? )); then
    echo "${RUN} Failed: $?"
else
    echo "${RUN} Exiting."
fi
